site_name: Data Quality Validation Platform
site_description: A reusable Python application for automating dataset validation and reporting
site_url: https://devminda.github.io/data-validator/
repo_url: https://github.com/devminda/data-validator
repo_name: devminda/data-validator
dev_addr: 127.0.0.1:8000

theme:
  name: material
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - search.suggest

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: [src]
          options:
            show_source: true
            docstring_style: google

nav:
  - Home: index.md
  - Clients Requirements: requirements.md
  - API Reference:
      - Overview: api/index.md
  - Development: development.md
